conv_software_paths:
  convbin : "convbin"
  leica : "mdb2rinex"
  septentrio : "sbf2rin"
  topcon : "tps2rin.exe"
  trimble : "trm2rinex:cli-light"
  trimble_runpkr00 : "runpkr00"
  ### RINEX handeling
  converto : "ConvertoCPP"
  gfzrnx : "gfzrnx"
  teqc : "teqc"
general:
  log_verbosity: "DEBUG"
