### other structure for the session(s) 

station:
    site: HOUE00GLP
    sitelog_path:
    antenna:
        device_attributes_from_sitelog: True
        manufacturer: LEICA
        model: AS10
        serial_number: 
    receiver: 
        device_attributes_from_sitelog: True
        manufacturer: AUTO_FROM_SITELOG # code IGS code files https://files.igs.org/pub/station/general/rcvr_ant.tab
        model: AUTO_FROM_SITELOG
        serial_number: 123456789
    access:
        protocol: "ftp"
        hostname: "gps-houe.terrain.ovsg.univ-ag.fr"
        login: "root"
        password: "ovsg13;:"
    sessions_list:
      - session:
            name: HOUE_30s_MDB # if differs from session_name
            remote_dir: "/SD Card/Data/<name>/<SITE4>/%Y/%m/%d"
            remote_fname:  "<SITE4>%j0.m00"
            file_period: "01D" # RINEX convention (01D, 01H etc...)
            data_frequency: "30S" # RINEX convention (XXC – 100 Hertz, XXZ – Hertz, XXS – Seconds, XXM – Minutes, XXH – Hours, XXD – Days, XXU – Unspecified)
        epoch_range:
            epoch1: '2 days ago at 14:00'
            epoch2: '3 days ago at midnight'
            round_method: "ceil"
            tz : 'UTC'
        workflow:
            log_parent_dir:
            log_dir_structure: <SITE9>/%Y/%j  
            download:
                active: True
                output_dir_parent: /home/gps/tests_pierres/dltest/
                output_dir_structure: <SITE4>/%Y/%j
            rinex_conversion:
                active: True
                converter : auto
                output_dir_parent: 
                output_dir_structure: <SITE9>/%Y/%j
                log_dir_parent:
                log_dir_structure: <SITE9>/%Y/%j      
            rinex_header_mod:
                active: True
                output_dir_parent: 
                output_dir_structure: <SITE9>/%Y/%j
