### other structure for the session(s) 

station:
    site: PSA100GLP
    sitelog_path:
    #geodesyml_path:
    antenna:
        device_attributes_from_sitelog: True
        manufacturer: LEICA
        model: AS10
        serial_number: 
    receiver: 
        device_attributes_from_sitelog: True
        manufacturer: AUTO_FROM_SITELOG # code IGS code files https://files.igs.org/pub/station/general/rcvr_ant.tab
        model: AUTO_FROM_SITELOG
        serial_number: 123456789
    access:
        protocol: "http"
        hostname: "http://gps-psa.terrain.ovsg.univ-ag.fr"
        login: ""
        password: ""
    sessions_list:
      - session:
            name: 01D_30S # if differs from session_name
            remote_dir: "download/Internal/%Y%m/"
            remote_fname:  "<SITE4>______%Y%m%d%H%MA.T02"
            file_period: "01D" # seconds or RINEX convention (01D, 01H etc...)
            data_frequency: 30 # seconds or RINEX convention (XXC – 100 Hertz, XXZ – Hertz, XXS – Seconds, XXM – Minutes, XXH – Hours, XXD – Days, XXU – Unspecified)
        request:
            download:
                active: True
                output_dir_parent: /home/gps/tests_pierres/dltest/
                output_dir_structure: <SITE4>/%Y/%j
                log_parent_dir:
                log_dir_structure: <SITE9>/%Y/%j  
                epoch_range:
                    epoch1: '2 days ago at 14:00'
                    epoch2: '3 days ago at midnight'
                    round_method: "ceil"
                    tz : 'UTC'
            rinex_conversion:
                active: True
                output_dir_parent: 
                output_dir_structure: <SITE9>/%Y/%j
                log_dir_parent:
                log_dir_structure: <SITE9>/%Y/%j      
            rinex_splicing:
                active: True
                output_dir_parent: 
                output_dir_structure: <SITE9>/%Y/%j      
                log_dir_parent:
                log_dir_structure: <SITE9>/%Y/%j  
            rinex_decimation:
            rinex_spliting:
      - session:
            name: 01H_01S # if differs from session_name
            remote_dir: "download/Internal/%Y%m/"
            remote_fname:  "<SITE4>______%Y%m%d%H%MB.T02"
            file_period: "01H" # seconds or RINEX convention (01D, 01H etc...)
            data_frequency: 30 # seconds or RINEX convention (XXC – 100 Hertz, XXZ – Hertz, XXS – Seconds, XXM – Minutes, XXH – Hours, XXD – Days, XXU – Unspecified)
        request:
            download:
                active: True
                output_dir_parent: /home/gps/tests_pierres/dltest/
                output_dir_structure: <SITE4>/%Y/%j
                log_parent_dir:
                log_dir_structure: <SITE9>/%Y/%j  
                epoch_range:
                    epoch1: '2 days ago at 14:00'
                    epoch2: '3 days ago at midnight'

