station:
    coder: TOTO00FRA
    sitelog_path:
    #geodesyml_path:
    antenna:
        device_attributes_from_sitelog: True
        manufacturer: LEICA
        model: AS10
        serial_number: 
    receiver: 
        device_attributes_from_sitelog: True
        manufacturer: AUTO_FROM_SITELOG # code IGS code files https://files.igs.org/pub/station/general/rcvr_ant.tab
        model: AUTO_FROM_SITELOG
        serial_number: 123456789
        access:
            protocol:
            hostname:
            login:
            password:
        sessions:
          - session:
                name: &ses_name1 session1
                name_on_receiver: *ses_name1 # if differs from session_name
                path_structure:  <CODE9>/%Y/%j
                name_structure:  <CODE9><YYYY><HH>.t02
                file_period: 3600 # seconds or RINEX convention (01D, 01H etc...)
                data_frequency: 1 # seconds or RINEX convention (XXC – 100 Hertz, XXZ – Hertz, XXS – Seconds, XXM – Minutes, XXH – Hours, XXD – Days, XXU – Unspecified)
                
                download:
                    active: True
                    output_dir_parent: 
                    output_dir_structure: <CODE9>/%Y/%j
                    log_parent_dir:
                    log_dir_structure: <CODE9>/%Y/%j  
                    timespan:
                        mode: relative_to_an_epoch
                        between_start_end_epochs:
                            start_epoch: ### must support year/doy, gpsweek/dow, juliandate, classic year/month/day + hours
                            end_epoch:
                        relative_to_an_epoch:
                            before_or_after: before
                            epoch: now previous_midnight <absolute_value>
                            duration:
                        
                rinex_conversion:
                    active: True
                    output_dir_parent: 
                    output_dir_structure: <CODE9>/%Y/%j
                    log_dir_parent:
                    log_dir_structure: <CODE9>/%Y/%j      
                rinex_splicing:
                    active: True
                    output_dir_parent: 
                    output_dir_structure: <CODE9>/%Y/%j      
                    log_dir_parent:
                    log_dir_structure: <CODE9>/%Y/%j  
                rinex_decimation:
                rinex_spliting:
          - session: 
                name: &ses_name2 session2
                name_on_receiver: *ses_name2 # if differs from session_name
                path_structure:  <CODE4>/<GPSWEEK>/<DOW>
                name_structure:  <CODE9><YYYY><HH>.t02
                period_length: 3600 # seconds or RINEX convention (01D, 01H etc...)
